/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panda_org_angrypandanativees_basic_rl_CubeRenderer */

#ifndef _Included_com_panda_org_angrypandanativees_basic_rl_CubeRenderer
#define _Included_com_panda_org_angrypandanativees_basic_rl_CubeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_CubeRenderer
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_panda_org_angrypandanativees_basic_rl_CubeRenderer_init
  (JNIEnv *, jobject);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_CubeRenderer
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_CubeRenderer_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_CubeRenderer
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_CubeRenderer_render
  (JNIEnv *, jobject);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_CubeRenderer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_CubeRenderer_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
