/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panda_org_angrypandanativees_basic_rl_RendererNatives */

#ifndef _Included_com_panda_org_angrypandanativees_basic_rl_RendererNatives
#define _Included_com_panda_org_angrypandanativees_basic_rl_RendererNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_RendererNatives
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_panda_org_angrypandanativees_basic_rl_RendererNatives_init
  (JNIEnv *, jobject);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_RendererNatives
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_RendererNatives_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_RendererNatives
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_RendererNatives_step
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
