/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panda_org_angrypandanativees_basic_rl_RectRenderer */

#ifndef _Included_com_panda_org_angrypandanativees_basic_rl_RectRenderer
#define _Included_com_panda_org_angrypandanativees_basic_rl_RectRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_RectRenderer
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_panda_org_angrypandanativees_basic_rl_RectRenderer_init
  (JNIEnv *, jobject);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_RectRenderer
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_RectRenderer_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_RectRenderer
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_RectRenderer_step
  (JNIEnv *, jobject);

/*
 * Class:     com_panda_org_angrypandanativees_basic_rl_RectRenderer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandanativees_basic_rl_RectRenderer_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
